#!/usr/bin/env bash
set -ex

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

rm -f ~/.bash_profile ~/.bashrc ~/.gitignore ~/.gitconfig ~/.gvimrc ~/.vimrc ~/.vim ~/.toprc ~/.screenrc ~/.rdebugrc ~/.ackrc ~/.rdebugrc ~/.ctags ~/.pryrc ~/.gemrc

if [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    sudo apt-get install -f -y git fish autojump vim-nox curl
    sudo apt-get update
else
    ./homebrews.sh
fi

chsh -s /usr/bin/fish

ln -vs $DIR/bash/bash_profile ~/.bash_profile
ln -vs $DIR/bash/bashrc ~/.bashrc
ln -vs $DIR/git/gitignore ~/.gitignore
ln -vs $DIR/git/gitconfig ~/.gitconfig
ln -vs $DIR/vim/gvimrc ~/.gvimrc
ln -vs $DIR/vim/vimrc ~/.vimrc
ln -vs $DIR/vim/ ~/.vim
ln -vs $DIR/screenrc ~/.screenrc
ln -vs $DIR/toprc ~/.toprc
ln -vs $DIR/ackrc ~/.ackrc
ln -vs $DIR/rdebugrc ~/.rdebugrc
ln -vs $DIR/ctags ~/.ctags
ln -vs $DIR/pryrc ~/.pryrc
ln -vs $DIR/gemrc ~/.gemrc

mkdir -p ~/.config/
ln -fvs $DIR/fish ~/.config
fish -c "curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher"
fish -c "fisher install lilyball/nix-env.fish"

mkdir -p ~/.lein/
ln -fvs $DIR/leinrc ~/.lein/leinrc

git config --global core.excludesfile ~/.gitignore
mkdir -p ~/.vim_backup

mkdir -p ~/bin