source "$HOME/dotfiles/bash/bashrc"
source "$HOME/dotfiles/bash/autojump"
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"
export NARWHAL_ENGINE=jsc

export PATH="/usr/local/narwhal/bin:$PATH"
